pull_request_rules:
  - name: automatic merge sileht stuffs
    conditions:
      - base=master3
      - label!=work-in-progress
      - label!=manual merge
    actions:
      merge:
        strict: "smart"
        method: rebase